//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestScore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreCard
    {
        public int ScoreId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public Nullable<int> MissedQuestions { get; set; }
    }
}
